baseURL = "https://thnhan1.github.io/githup-blog/"
languageCode = "vn-vi"
title = "Nhan's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Huu Nhan"
  description = "Life is short, Live it well!"
  github = "thnhan1"
  facebook = "thnhan1"
  twitter = "nhanthatsu"
  linkedin = "thnhan1"
  instagram = "thnhan1"
  tumblr = "thnhan1"
  email = "nhandev10@gmail.com"
  url = "https://thnhan1.com"
  keywords = "blog, google analytics, java, developer, software"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/githup-blog/images/github.jpg"
  avatar = "/githup-blog/images/avatar.jpg"
  headerIcon = "/githup-blog/images/GitHub-Mark-Light-32px.png"
  location = "China"
  enableGitalk = true
  custom_css = ["/githup-blog/css/custom.css"]
  custom_js = ["/githup-blog/js/custom.js"]
  enableSearch = true

[outputs]
 home = ["html", "json"]

[outputFormats.json]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = false

#   [params.gitalk]
#     clientID = "Your client ID"
#     clientSecret = "Your client secret"
#     repo = "repo"
#     owner = "thnhan1"
#     admin = "thnhan1"
#     id = "location.pathname"
#     labels = "gitalk"
#     perPage = 15
#     pagerDirection = "last"
#     createIssueManually = true
#     distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://thnhan1.github.io/githup-blog/"
  [[params.links]]
    title = "Link2"
    href = "https://thnhan1.github.io/githup-blog/"
    icon = "/images/avatar.jpg"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

# [services]
#   [services.googleAnalytics]
#     ID = "UA-123456-789"
